CREATE DATABASE IF NOT EXISTS 'dummysymfony';
CREATE DATABASE IF NOT EXISTS 'testsymfony';
CREATE USER IF NOT EXISTS 'kalasymfony'@'%' IDENTIFIED BY 'kalasymfony654';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, TRIGGER
    ON *.* TO 'kalasymfony'@'%';
FLUSH PRIVILEGES;
